#!/bin/bash

set -e

MANAGE=./manage

cd $(dirname $0)
source ./config

FUNCTIONAPP_DIR=$(realpath $FUNCTIONAPP_DIR)
NGINX_DIR=$(realpath $NGINX_DIR)

# Export all config vars
#
export $(awk '
	BEGIN { FS = "=" }
	{ print $1 }
' <./config)

CMD=$1
shift

case $CMD in

	(docker) _DOCKER_ARGS="$@" exec $MANAGE _docker ;;

	(sh|shell) _DOCKER_ARGS="exec $1 sh" exec $MANAGE _docker ;;

	(_docker)
		env $DOCKER_ENV docker-compose \
			-p$PROJECT_NAME \
			-f./docker/docker-compose.yml \
			$_DOCKER_ARGS
		;;

	(*) echo "$CMD: Unknown command";;
esac
