version: '3.5'
services:
    functionapp:
        build: './functionapp'
        volumes:
            - '$FUNCTIONAPP_DIR:/home/azure/functionapp:ro'
        ports:
            - '$FUNCTIONAPP_PORT:7071'
        networks:
            cloud:

    mongo:
        build: './mongo'
        volumes:
            - 'database:/var/db'
        networks:
            cloud:
                aliases:
                    - 'mongo'

    nginx:
        build: './nginx'
        volumes:
            - '$NGINX_DIR:/var/www/data:ro'
        ports:
            - '$NGINX_PORT:80'

    serverapp:
        build: './serverapp'
        environment:
            CORS_ALLOWED_ORIGINS: '$CORS_ALLOWED_ORIGINS'
            MONGO_URL: 'mongodb://mongo:27017/develop'
            PORT: '8000'
        volumes:
            - '$SERVERAPP_DIR:/opt/service/app:ro'
        ports:
            - '$SERVERAPP_PORT:8000'
        networks:
            cloud:

networks:
    cloud:

volumes:
    database:
